language: python
python: 3.8
dist: bionic
env:
  global:
    - DRF="djangorestframework==3.11.0"
    - DJANGO="django==3.0.2"
matrix:
  include:
    - name: "Defaults (Python 3.8, Django 3.0, DRF 3.11)"
    - name: "+ SpatiaLite"
      env:
        - WITH_GIS=1
      addons:
        apt:
          packages:
           - libsqlite3-mod-spatialite
           - gdal-bin
    - name: "+ PostGIS"
      env:
        - PSYCOPG2="psycopg2-binary"
        - WITH_GIS=1
      addons:
        postgresql: "10"
        apt:
          packages:
           - postgresql-10-postgis-2.4
      before_script:
       - createdb -Upostgres wqdb_test
       - psql -Upostgres wqdb_test -c "CREATE EXTENSION postgis;"
    - name: "+ Non-Root Base URL"
      env:
        - WITH_NONROOT=1
    - name: "Python 3.7"
      python: "3.7"
    - name: "Python 3.6"
      python: "3.6"
    - name: "Django 2.2"
      env:
        - DJANGO="django==2.2.9"
    - name: "Django 1.11"
      env:
        - DJANGO="django==1.11.27"
    - name: "Django 1.11 + PostGIS"
      env:
        - DJANGO="django==1.11.27"
        - PSYCOPG2="psycopg2-binary"
        - WITH_GIS=1
      addons:
        postgresql: "10"
        apt:
          packages:
           - postgresql-10-postgis-2.4
      before_script:
       - createdb -Upostgres wqdb_test
       - psql -Upostgres wqdb_test -c "CREATE EXTENSION postgis;"
    - name: "Python 3.5, Django 2.2"
      python: "3.5"
      env:
        - DJANGO="django==2.2.9"
    - name: "Python 3.4, Django 2.0, DRF 3.9"
      dist: xenial
      python: "3.4"
      env:
        - DJANGO="django==2.0.13"
        - DRF="djangorestframework==3.9.4"
    - name: "Code Lint"
      env:
        - LINT="flake8"
install:
 - pip install $DJANGO $DRF $PSYCOPG2 $LINT
script:
 - ./runtests.sh
